name: Deno CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: curl -fsSL https://deno.land/x/install/install.sh | sh
    - run: deno ifno
    - run: deno cache --config ./tsconfig.app.json alosaur.ts # Loads cource code and compiles it https://deno.land/manual/runtime/compiler_apis
    # - run: deno bundle --config .\tsconfig.app.json .\alosaur.ts # Fails beacuse of "ky" imported as js file in /api/* files
    - run: deno test
